# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-07-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180704_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(help_text='(MM/DD/YYYY)'),
        ),
    ]
