# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180629_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='./user_profile_avatar'),
        ),
    ]
